# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_NMR(object):
    def setupUi(self, MainWindow_NMR):
        MainWindow_NMR.setObjectName("MainWindow_NMR")
        MainWindow_NMR.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow_NMR.resize(1110, 669)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_NMR.sizePolicy().hasHeightForWidth())
        MainWindow_NMR.setSizePolicy(sizePolicy)
        MainWindow_NMR.setMinimumSize(QtCore.QSize(1110, 420))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow_NMR.setFont(font)
        MainWindow_NMR.setAutoFillBackground(False)
        MainWindow_NMR.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow_NMR)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWinget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWinget.setGeometry(QtCore.QRect(0, 0, 1111, 641))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWinget.setFont(font)
        self.tabWinget.setObjectName("tabWinget")
        self.Tab_referenceMesurement = QtWidgets.QWidget()
        self.Tab_referenceMesurement.setObjectName("Tab_referenceMesurement")
        self.groupBox_temperature = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_temperature.setGeometry(QtCore.QRect(10, 45, 350, 32))
        self.groupBox_temperature.setTitle("")
        self.groupBox_temperature.setObjectName("groupBox_temperature")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_temperature)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_temperature = QtWidgets.QLabel(self.groupBox_temperature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_temperature.sizePolicy().hasHeightForWidth())
        self.label_temperature.setSizePolicy(sizePolicy)
        self.label_temperature.setObjectName("label_temperature")
        self.horizontalLayout_4.addWidget(self.label_temperature)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.plainTextEdit_temperature = QtWidgets.QPlainTextEdit(self.groupBox_temperature)
        self.plainTextEdit_temperature.setObjectName("plainTextEdit_temperature")
        self.horizontalLayout_4.addWidget(self.plainTextEdit_temperature)
        self.groupBox_user = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_user.setGeometry(QtCore.QRect(10, 10, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_user.setFont(font)
        self.groupBox_user.setTitle("")
        self.groupBox_user.setFlat(False)
        self.groupBox_user.setCheckable(False)
        self.groupBox_user.setObjectName("groupBox_user")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_user)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_user = QtWidgets.QLabel(self.groupBox_user)
        self.label_user.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user.sizePolicy().hasHeightForWidth())
        self.label_user.setSizePolicy(sizePolicy)
        self.label_user.setObjectName("label_user")
        self.horizontalLayout.addWidget(self.label_user)
        spacerItem1 = QtWidgets.QSpacerItem(74, 74, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.plainTextEdit_user = QtWidgets.QPlainTextEdit(self.groupBox_user)
        self.plainTextEdit_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_user.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_user.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_user.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_user.setObjectName("plainTextEdit_user")
        self.horizontalLayout.addWidget(self.plainTextEdit_user)
        self.groupBox_language = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_language.setGeometry(QtCore.QRect(10, 80, 100, 70))
        self.groupBox_language.setTitle("")
        self.groupBox_language.setObjectName("groupBox_language")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_language)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_language = QtWidgets.QLabel(self.groupBox_language)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.verticalLayout.addWidget(self.label_language)
        self.checkBox_language_german = QtWidgets.QCheckBox(self.groupBox_language)
        self.checkBox_language_german.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_language_german.setChecked(True)
        self.checkBox_language_german.setTristate(False)
        self.checkBox_language_german.setObjectName("checkBox_language_german")
        self.verticalLayout.addWidget(self.checkBox_language_german)
        self.checkBox_language_english = QtWidgets.QCheckBox(self.groupBox_language)
        self.checkBox_language_english.setObjectName("checkBox_language_english")
        self.verticalLayout.addWidget(self.checkBox_language_english)
        self.groupBox_dateTime = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_dateTime.setEnabled(True)
        self.groupBox_dateTime.setGeometry(QtCore.QRect(110, 80, 140, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_dateTime.setFont(font)
        self.groupBox_dateTime.setTitle("")
        self.groupBox_dateTime.setObjectName("groupBox_dateTime")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_dateTime)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_dateTime = QtWidgets.QLabel(self.groupBox_dateTime)
        self.label_dateTime.setObjectName("label_dateTime")
        self.verticalLayout_2.addWidget(self.label_dateTime)
        self.dateTimeEdit_dateTime = QtWidgets.QDateTimeEdit(self.groupBox_dateTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_dateTime.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_dateTime.setSizePolicy(sizePolicy)
        self.dateTimeEdit_dateTime.setObjectName("dateTimeEdit_dateTime")
        self.verticalLayout_2.addWidget(self.dateTimeEdit_dateTime)
        self.groupBox_materialName = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_materialName.setGeometry(QtCore.QRect(380, 43, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_materialName.setFont(font)
        self.groupBox_materialName.setTitle("")
        self.groupBox_materialName.setFlat(False)
        self.groupBox_materialName.setCheckable(False)
        self.groupBox_materialName.setObjectName("groupBox_materialName")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_materialName)
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_materialName = QtWidgets.QLabel(self.groupBox_materialName)
        self.label_materialName.setObjectName("label_materialName")
        self.horizontalLayout_5.addWidget(self.label_materialName)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.comboBox_materialName = QtWidgets.QComboBox(self.groupBox_materialName)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_materialName.sizePolicy().hasHeightForWidth())
        self.comboBox_materialName.setSizePolicy(sizePolicy)
        self.comboBox_materialName.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_materialName.setAutoFillBackground(False)
        self.comboBox_materialName.setEditable(True)
        self.comboBox_materialName.setMaxVisibleItems(10)
        self.comboBox_materialName.setFrame(True)
        self.comboBox_materialName.setObjectName("comboBox_materialName")
        self.horizontalLayout_5.addWidget(self.comboBox_materialName)
        self.groupBox_evaluation = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_evaluation.setGeometry(QtCore.QRect(250, 80, 110, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_evaluation.setFont(font)
        self.groupBox_evaluation.setTitle("")
        self.groupBox_evaluation.setFlat(False)
        self.groupBox_evaluation.setCheckable(False)
        self.groupBox_evaluation.setObjectName("groupBox_evaluation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_evaluation)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_evaluation = QtWidgets.QLabel(self.groupBox_evaluation)
        self.label_evaluation.setObjectName("label_evaluation")
        self.verticalLayout_3.addWidget(self.label_evaluation)
        self.checkBox_evaluation_single = QtWidgets.QCheckBox(self.groupBox_evaluation)
        self.checkBox_evaluation_single.setChecked(True)
        self.checkBox_evaluation_single.setObjectName("checkBox_evaluation_single")
        self.verticalLayout_3.addWidget(self.checkBox_evaluation_single)
        self.checkBox_evaluation_other = QtWidgets.QCheckBox(self.groupBox_evaluation)
        self.checkBox_evaluation_other.setObjectName("checkBox_evaluation_other")
        self.verticalLayout_3.addWidget(self.checkBox_evaluation_other)
        self.groupBox_bulkName = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_bulkName.setGeometry(QtCore.QRect(750, 56, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_bulkName.setFont(font)
        self.groupBox_bulkName.setTitle("")
        self.groupBox_bulkName.setFlat(False)
        self.groupBox_bulkName.setCheckable(False)
        self.groupBox_bulkName.setObjectName("groupBox_bulkName")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_bulkName)
        self.horizontalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_bulkName = QtWidgets.QLabel(self.groupBox_bulkName)
        self.label_bulkName.setObjectName("label_bulkName")
        self.horizontalLayout_6.addWidget(self.label_bulkName)
        spacerItem3 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.comboBox_bulkName = QtWidgets.QComboBox(self.groupBox_bulkName)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_bulkName.sizePolicy().hasHeightForWidth())
        self.comboBox_bulkName.setSizePolicy(sizePolicy)
        self.comboBox_bulkName.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_bulkName.setAutoFillBackground(False)
        self.comboBox_bulkName.setEditable(True)
        self.comboBox_bulkName.setMaxVisibleItems(10)
        self.comboBox_bulkName.setFrame(True)
        self.comboBox_bulkName.setObjectName("comboBox_bulkName")
        self.horizontalLayout_6.addWidget(self.comboBox_bulkName)
        self.groupBox_remarks = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_remarks.setGeometry(QtCore.QRect(10, 170, 1090, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_remarks.setFont(font)
        self.groupBox_remarks.setTitle("")
        self.groupBox_remarks.setFlat(False)
        self.groupBox_remarks.setCheckable(False)
        self.groupBox_remarks.setObjectName("groupBox_remarks")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_remarks)
        self.horizontalLayout_8.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_remarks = QtWidgets.QLabel(self.groupBox_remarks)
        self.label_remarks.setObjectName("label_remarks")
        self.horizontalLayout_8.addWidget(self.label_remarks)
        spacerItem4 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.plainTextEdit_remarks = QtWidgets.QPlainTextEdit(self.groupBox_remarks)
        self.plainTextEdit_remarks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_remarks.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_remarks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_remarks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_remarks.setObjectName("plainTextEdit_remarks")
        self.horizontalLayout_8.addWidget(self.plainTextEdit_remarks)
        self.groupBox_surfaceArea_Argon = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_surfaceArea_Argon.setGeometry(QtCore.QRect(380, 80, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceArea_Argon.setFont(font)
        self.groupBox_surfaceArea_Argon.setTitle("")
        self.groupBox_surfaceArea_Argon.setFlat(False)
        self.groupBox_surfaceArea_Argon.setCheckable(False)
        self.groupBox_surfaceArea_Argon.setObjectName("groupBox_surfaceArea_Argon")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_surfaceArea_Argon)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_surfaceArea_Argon = QtWidgets.QLabel(self.groupBox_surfaceArea_Argon)
        self.label_surfaceArea_Argon.setObjectName("label_surfaceArea_Argon")
        self.horizontalLayout_2.addWidget(self.label_surfaceArea_Argon)
        spacerItem5 = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.plainTextEdit_surfaceArea_Argon = QtWidgets.QPlainTextEdit(self.groupBox_surfaceArea_Argon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_surfaceArea_Argon.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_surfaceArea_Argon.setSizePolicy(sizePolicy)
        self.plainTextEdit_surfaceArea_Argon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_surfaceArea_Argon.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceArea_Argon.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceArea_Argon.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_surfaceArea_Argon.setObjectName("plainTextEdit_surfaceArea_Argon")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_surfaceArea_Argon)
        self.groupBox_densityBulk = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_densityBulk.setGeometry(QtCore.QRect(750, 102, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_densityBulk.setFont(font)
        self.groupBox_densityBulk.setTitle("")
        self.groupBox_densityBulk.setFlat(False)
        self.groupBox_densityBulk.setCheckable(False)
        self.groupBox_densityBulk.setObjectName("groupBox_densityBulk")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_densityBulk)
        self.horizontalLayout_7.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_densityBulk = QtWidgets.QLabel(self.groupBox_densityBulk)
        self.label_densityBulk.setObjectName("label_densityBulk")
        self.horizontalLayout_7.addWidget(self.label_densityBulk)
        spacerItem6 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.plainTextEdit_densityBulk = QtWidgets.QPlainTextEdit(self.groupBox_densityBulk)
        self.plainTextEdit_densityBulk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_densityBulk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_densityBulk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_densityBulk.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_densityBulk.setObjectName("plainTextEdit_densityBulk")
        self.horizontalLayout_7.addWidget(self.plainTextEdit_densityBulk)
        self.groupBox_mesurementFiles = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_mesurementFiles.setGeometry(QtCore.QRect(10, 220, 1090, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_mesurementFiles.sizePolicy().hasHeightForWidth())
        self.groupBox_mesurementFiles.setSizePolicy(sizePolicy)
        self.groupBox_mesurementFiles.setObjectName("groupBox_mesurementFiles")
        self.tableView_mesurementFiles = QtWidgets.QTableView(self.groupBox_mesurementFiles)
        self.tableView_mesurementFiles.setGeometry(QtCore.QRect(10, 20, 1080, 269))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableView_mesurementFiles.setFont(font)
        self.tableView_mesurementFiles.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_mesurementFiles.setWordWrap(True)
        self.tableView_mesurementFiles.setObjectName("tableView_mesurementFiles")
        self.line_2 = QtWidgets.QFrame(self.Tab_referenceMesurement)
        self.line_2.setGeometry(QtCore.QRect(360, 10, 20, 140))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.Tab_referenceMesurement)
        self.line_4.setGeometry(QtCore.QRect(10, 150, 1091, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_AddMesurementFiles = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_AddMesurementFiles.setGeometry(QtCore.QRect(20, 516, 190, 30))
        self.pushButton_AddMesurementFiles.setObjectName("pushButton_AddMesurementFiles")
        self.pushButton_RemoveAllMesurementFiles = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_RemoveAllMesurementFiles.setGeometry(QtCore.QRect(20, 549, 190, 30))
        self.pushButton_RemoveAllMesurementFiles.setObjectName("pushButton_RemoveAllMesurementFiles")
        self.pushButton_run_MeasurementFile = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_run_MeasurementFile.setGeometry(QtCore.QRect(920, 520, 130, 57))
        self.pushButton_run_MeasurementFile.setObjectName("pushButton_run_MeasurementFile")
        self.groupBox_particleDensity = QtWidgets.QGroupBox(self.Tab_referenceMesurement)
        self.groupBox_particleDensity.setGeometry(QtCore.QRect(380, 118, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_particleDensity.setFont(font)
        self.groupBox_particleDensity.setTitle("")
        self.groupBox_particleDensity.setFlat(False)
        self.groupBox_particleDensity.setCheckable(False)
        self.groupBox_particleDensity.setObjectName("groupBox_particleDensity")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_particleDensity)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_particleDensity = QtWidgets.QLabel(self.groupBox_particleDensity)
        self.label_particleDensity.setObjectName("label_particleDensity")
        self.horizontalLayout_3.addWidget(self.label_particleDensity)
        spacerItem7 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.plainTextEdit_particleDensity = QtWidgets.QPlainTextEdit(self.groupBox_particleDensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_particleDensity.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_particleDensity.setSizePolicy(sizePolicy)
        self.plainTextEdit_particleDensity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_particleDensity.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_particleDensity.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_particleDensity.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_particleDensity.setObjectName("plainTextEdit_particleDensity")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_particleDensity)
        self.line_5 = QtWidgets.QFrame(self.Tab_referenceMesurement)
        self.line_5.setGeometry(QtCore.QRect(730, 10, 20, 140))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_AddMaterial = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_AddMaterial.setGeometry(QtCore.QRect(380, 10, 171, 27))
        self.pushButton_AddMaterial.setObjectName("pushButton_AddMaterial")
        self.pushButton_RemoveMaterial = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_RemoveMaterial.setGeometry(QtCore.QRect(560, 10, 171, 27))
        self.pushButton_RemoveMaterial.setObjectName("pushButton_RemoveMaterial")
        self.pushButton_AddBulk = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_AddBulk.setGeometry(QtCore.QRect(750, 20, 171, 27))
        self.pushButton_AddBulk.setObjectName("pushButton_AddBulk")
        self.pushButton_RemoveBulk = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_RemoveBulk.setGeometry(QtCore.QRect(930, 20, 171, 27))
        self.pushButton_RemoveBulk.setObjectName("pushButton_RemoveBulk")
        self.pushButton_RemoveSelectedMeasrementFiles = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_RemoveSelectedMeasrementFiles.setGeometry(QtCore.QRect(220, 516, 190, 30))
        self.pushButton_RemoveSelectedMeasrementFiles.setObjectName("pushButton_RemoveSelectedMeasrementFiles")
        self.plainTextEdit_RemoveSelectedFilesMeasrementFiles = QtWidgets.QPlainTextEdit(self.Tab_referenceMesurement)
        self.plainTextEdit_RemoveSelectedFilesMeasrementFiles.setGeometry(QtCore.QRect(221, 550, 188, 30))
        self.plainTextEdit_RemoveSelectedFilesMeasrementFiles.setObjectName("plainTextEdit_RemoveSelectedFilesMeasrementFiles")
        self.comboBox_selectWeighInData = QtWidgets.QComboBox(self.Tab_referenceMesurement)
        self.comboBox_selectWeighInData.setGeometry(QtCore.QRect(468, 516, 188, 30))
        self.comboBox_selectWeighInData.setEditable(False)
        self.comboBox_selectWeighInData.setObjectName("comboBox_selectWeighInData")
        self.pushButton_SetUpdateWeights = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_SetUpdateWeights.setGeometry(QtCore.QRect(467, 550, 190, 30))
        self.pushButton_SetUpdateWeights.setObjectName("pushButton_SetUpdateWeights")
        self.line = QtWidgets.QFrame(self.Tab_referenceMesurement)
        self.line.setGeometry(QtCore.QRect(440, 520, 3, 60))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.Tab_referenceMesurement)
        self.line_3.setGeometry(QtCore.QRect(884, 520, 3, 60))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.plainTextEdit_SetUpdateWeights = QtWidgets.QPlainTextEdit(self.Tab_referenceMesurement)
        self.plainTextEdit_SetUpdateWeights.setGeometry(QtCore.QRect(665, 550, 188, 30))
        self.plainTextEdit_SetUpdateWeights.setObjectName("plainTextEdit_SetUpdateWeights")
        self.pushButton_SetUpdateSelectedWeights = QtWidgets.QPushButton(self.Tab_referenceMesurement)
        self.pushButton_SetUpdateSelectedWeights.setGeometry(QtCore.QRect(664, 517, 190, 30))
        self.pushButton_SetUpdateSelectedWeights.setObjectName("pushButton_SetUpdateSelectedWeights")
        self.tabWinget.addTab(self.Tab_referenceMesurement, "")
        self.tab_comperisonPlots = QtWidgets.QWidget()
        self.tab_comperisonPlots.setObjectName("tab_comperisonPlots")
        self.groupBox_comperisonPlots_T1_T2 = QtWidgets.QGroupBox(self.tab_comperisonPlots)
        self.groupBox_comperisonPlots_T1_T2.setGeometry(QtCore.QRect(20, 8, 1061, 91))
        self.groupBox_comperisonPlots_T1_T2.setTitle("")
        self.groupBox_comperisonPlots_T1_T2.setObjectName("groupBox_comperisonPlots_T1_T2")
        self.checkBox_comperisonPlots_T1 = QtWidgets.QCheckBox(self.groupBox_comperisonPlots_T1_T2)
        self.checkBox_comperisonPlots_T1.setGeometry(QtCore.QRect(20, 10, 181, 30))
        self.checkBox_comperisonPlots_T1.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_comperisonPlots_T1.setChecked(True)
        self.checkBox_comperisonPlots_T1.setObjectName("checkBox_comperisonPlots_T1")
        self.checkBox_comperisonPlots_T2 = QtWidgets.QCheckBox(self.groupBox_comperisonPlots_T1_T2)
        self.checkBox_comperisonPlots_T2.setGeometry(QtCore.QRect(20, 50, 181, 30))
        self.checkBox_comperisonPlots_T2.setChecked(True)
        self.checkBox_comperisonPlots_T2.setObjectName("checkBox_comperisonPlots_T2")
        self.plainTextEdit_comperisonPlots_comperisonPlots_T1PlotName = QtWidgets.QPlainTextEdit(self.groupBox_comperisonPlots_T1_T2)
        self.plainTextEdit_comperisonPlots_comperisonPlots_T1PlotName.setGeometry(QtCore.QRect(350, 10, 691, 30))
        self.plainTextEdit_comperisonPlots_comperisonPlots_T1PlotName.setObjectName("plainTextEdit_comperisonPlots_comperisonPlots_T1PlotName")
        self.label_comperisonPlots_T1PlotName = QtWidgets.QLabel(self.groupBox_comperisonPlots_T1_T2)
        self.label_comperisonPlots_T1PlotName.setGeometry(QtCore.QRect(230, 10, 111, 30))
        self.label_comperisonPlots_T1PlotName.setObjectName("label_comperisonPlots_T1PlotName")
        self.line_comperisonPlots_T1_T2 = QtWidgets.QFrame(self.groupBox_comperisonPlots_T1_T2)
        self.line_comperisonPlots_T1_T2.setGeometry(QtCore.QRect(210, 10, 3, 61))
        self.line_comperisonPlots_T1_T2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_comperisonPlots_T1_T2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_comperisonPlots_T1_T2.setObjectName("line_comperisonPlots_T1_T2")
        self.plainTextEdit_T1_PlotName = QtWidgets.QPlainTextEdit(self.groupBox_comperisonPlots_T1_T2)
        self.plainTextEdit_T1_PlotName.setGeometry(QtCore.QRect(350, 50, 691, 30))
        self.plainTextEdit_T1_PlotName.setObjectName("plainTextEdit_T1_PlotName")
        self.label_comperisonPlots_T2PlotName = QtWidgets.QLabel(self.groupBox_comperisonPlots_T1_T2)
        self.label_comperisonPlots_T2PlotName.setGeometry(QtCore.QRect(230, 50, 111, 30))
        self.label_comperisonPlots_T2PlotName.setObjectName("label_comperisonPlots_T2PlotName")
        self.groupBox_comperisonPlots_language = QtWidgets.QGroupBox(self.tab_comperisonPlots)
        self.groupBox_comperisonPlots_language.setGeometry(QtCore.QRect(20, 103, 100, 91))
        self.groupBox_comperisonPlots_language.setTitle("")
        self.groupBox_comperisonPlots_language.setObjectName("groupBox_comperisonPlots_language")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_comperisonPlots_language)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_comperisonPlots_language = QtWidgets.QLabel(self.groupBox_comperisonPlots_language)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_comperisonPlots_language.setFont(font)
        self.label_comperisonPlots_language.setObjectName("label_comperisonPlots_language")
        self.verticalLayout_7.addWidget(self.label_comperisonPlots_language)
        self.checkBox_comperisonPlots_language_german = QtWidgets.QCheckBox(self.groupBox_comperisonPlots_language)
        self.checkBox_comperisonPlots_language_german.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_comperisonPlots_language_german.setChecked(True)
        self.checkBox_comperisonPlots_language_german.setTristate(False)
        self.checkBox_comperisonPlots_language_german.setObjectName("checkBox_comperisonPlots_language_german")
        self.verticalLayout_7.addWidget(self.checkBox_comperisonPlots_language_german)
        self.checkBox_comperisonPlots_language_english = QtWidgets.QCheckBox(self.groupBox_comperisonPlots_language)
        self.checkBox_comperisonPlots_language_english.setChecked(True)
        self.checkBox_comperisonPlots_language_english.setObjectName("checkBox_comperisonPlots_language_english")
        self.verticalLayout_7.addWidget(self.checkBox_comperisonPlots_language_english)
        self.groupBox_comperisonPlots_calculationOfVolumeFraction = QtWidgets.QGroupBox(self.tab_comperisonPlots)
        self.groupBox_comperisonPlots_calculationOfVolumeFraction.setGeometry(QtCore.QRect(126, 103, 411, 91))
        self.groupBox_comperisonPlots_calculationOfVolumeFraction.setTitle("")
        self.groupBox_comperisonPlots_calculationOfVolumeFraction.setObjectName("groupBox_comperisonPlots_calculationOfVolumeFraction")
        self.plainTextEdit_comperisonPlots_T2_calculationOfVolumeFraction = QtWidgets.QPlainTextEdit(self.groupBox_comperisonPlots_calculationOfVolumeFraction)
        self.plainTextEdit_comperisonPlots_T2_calculationOfVolumeFraction.setGeometry(QtCore.QRect(260, 50, 141, 30))
        self.plainTextEdit_comperisonPlots_T2_calculationOfVolumeFraction.setObjectName("plainTextEdit_comperisonPlots_T2_calculationOfVolumeFraction")
        self.plainTextEdit_comperisonPlots_T1_calculationOfVolumeFraction = QtWidgets.QPlainTextEdit(self.groupBox_comperisonPlots_calculationOfVolumeFraction)
        self.plainTextEdit_comperisonPlots_T1_calculationOfVolumeFraction.setGeometry(QtCore.QRect(260, 10, 141, 30))
        self.plainTextEdit_comperisonPlots_T1_calculationOfVolumeFraction.setObjectName("plainTextEdit_comperisonPlots_T1_calculationOfVolumeFraction")
        self.label_T1_comperisonPlots_calculationOfVolumeFraction = QtWidgets.QLabel(self.groupBox_comperisonPlots_calculationOfVolumeFraction)
        self.label_T1_comperisonPlots_calculationOfVolumeFraction.setGeometry(QtCore.QRect(10, 10, 251, 30))
        self.label_T1_comperisonPlots_calculationOfVolumeFraction.setObjectName("label_T1_comperisonPlots_calculationOfVolumeFraction")
        self.label_T2_comperisonPlots_calculationOfVolumeFraction = QtWidgets.QLabel(self.groupBox_comperisonPlots_calculationOfVolumeFraction)
        self.label_T2_comperisonPlots_calculationOfVolumeFraction.setGeometry(QtCore.QRect(10, 50, 251, 30))
        self.label_T2_comperisonPlots_calculationOfVolumeFraction.setObjectName("label_T2_comperisonPlots_calculationOfVolumeFraction")
        self.groupBox_comperisonPlots_referenceMeasurementFiles = QtWidgets.QGroupBox(self.tab_comperisonPlots)
        self.groupBox_comperisonPlots_referenceMeasurementFiles.setGeometry(QtCore.QRect(10, 200, 1090, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_comperisonPlots_referenceMeasurementFiles.sizePolicy().hasHeightForWidth())
        self.groupBox_comperisonPlots_referenceMeasurementFiles.setSizePolicy(sizePolicy)
        self.groupBox_comperisonPlots_referenceMeasurementFiles.setObjectName("groupBox_comperisonPlots_referenceMeasurementFiles")
        self.tableView_comperisonPlots_referenceMeasurementFiles = QtWidgets.QTableView(self.groupBox_comperisonPlots_referenceMeasurementFiles)
        self.tableView_comperisonPlots_referenceMeasurementFiles.setGeometry(QtCore.QRect(10, 20, 1080, 269))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableView_comperisonPlots_referenceMeasurementFiles.setFont(font)
        self.tableView_comperisonPlots_referenceMeasurementFiles.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_comperisonPlots_referenceMeasurementFiles.setWordWrap(True)
        self.tableView_comperisonPlots_referenceMeasurementFiles.setObjectName("tableView_comperisonPlots_referenceMeasurementFiles")
        self.pushButton_comperisonPlots_RemoveSelectedReferenceMeasrementFiles = QtWidgets.QPushButton(self.tab_comperisonPlots)
        self.pushButton_comperisonPlots_RemoveSelectedReferenceMeasrementFiles.setGeometry(QtCore.QRect(310, 500, 261, 30))
        self.pushButton_comperisonPlots_RemoveSelectedReferenceMeasrementFiles.setObjectName("pushButton_comperisonPlots_RemoveSelectedReferenceMeasrementFiles")
        self.pushButton_comperisonPlots_AddReferenceReferenceMesurementFiles = QtWidgets.QPushButton(self.tab_comperisonPlots)
        self.pushButton_comperisonPlots_AddReferenceReferenceMesurementFiles.setGeometry(QtCore.QRect(20, 500, 261, 30))
        self.pushButton_comperisonPlots_AddReferenceReferenceMesurementFiles.setObjectName("pushButton_comperisonPlots_AddReferenceReferenceMesurementFiles")
        self.pushButton_comperisonPlots_RemoveAllReferenceMesurementFiles = QtWidgets.QPushButton(self.tab_comperisonPlots)
        self.pushButton_comperisonPlots_RemoveAllReferenceMesurementFiles.setGeometry(QtCore.QRect(20, 536, 261, 30))
        self.pushButton_comperisonPlots_RemoveAllReferenceMesurementFiles.setObjectName("pushButton_comperisonPlots_RemoveAllReferenceMesurementFiles")
        self.plainTextEdit_comperisonPlots_RemoveSelectedFilesReferenceMeasrementFiles = QtWidgets.QPlainTextEdit(self.tab_comperisonPlots)
        self.plainTextEdit_comperisonPlots_RemoveSelectedFilesReferenceMeasrementFiles.setGeometry(QtCore.QRect(310, 536, 261, 30))
        self.plainTextEdit_comperisonPlots_RemoveSelectedFilesReferenceMeasrementFiles.setObjectName("plainTextEdit_comperisonPlots_RemoveSelectedFilesReferenceMeasrementFiles")
        self.pushButton_ComerisonPlots_run = QtWidgets.QPushButton(self.tab_comperisonPlots)
        self.pushButton_ComerisonPlots_run.setGeometry(QtCore.QRect(920, 510, 130, 57))
        self.pushButton_ComerisonPlots_run.setObjectName("pushButton_ComerisonPlots_run")
        self.tabWinget.addTab(self.tab_comperisonPlots, "")
        self.tab_surfaceAreaCalculation = QtWidgets.QWidget()
        self.tab_surfaceAreaCalculation.setObjectName("tab_surfaceAreaCalculation")
        self.line_8 = QtWidgets.QFrame(self.tab_surfaceAreaCalculation)
        self.line_8.setGeometry(QtCore.QRect(360, 133, 20, 140))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton_surfaceAreaCalculation_RemoveMaterial = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_RemoveMaterial.setGeometry(QtCore.QRect(560, 133, 171, 27))
        self.pushButton_surfaceAreaCalculation_RemoveMaterial.setObjectName("pushButton_surfaceAreaCalculation_RemoveMaterial")
        self.pushButton_surfaceAreaCalculation_RemoveBulk = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_RemoveBulk.setGeometry(QtCore.QRect(930, 143, 171, 27))
        self.pushButton_surfaceAreaCalculation_RemoveBulk.setObjectName("pushButton_surfaceAreaCalculation_RemoveBulk")
        self.groupBox_surfaceAreaCalculation_remarks = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_remarks.setGeometry(QtCore.QRect(10, 293, 1090, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_remarks.setFont(font)
        self.groupBox_surfaceAreaCalculation_remarks.setTitle("")
        self.groupBox_surfaceAreaCalculation_remarks.setFlat(False)
        self.groupBox_surfaceAreaCalculation_remarks.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_remarks.setObjectName("groupBox_surfaceAreaCalculation_remarks")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_remarks)
        self.horizontalLayout_33.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_surfaceAreaCalculation_remarks = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_remarks)
        self.label_surfaceAreaCalculation_remarks.setObjectName("label_surfaceAreaCalculation_remarks")
        self.horizontalLayout_33.addWidget(self.label_surfaceAreaCalculation_remarks)
        spacerItem8 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem8)
        self.plainTextEdit_surfaceAreaCalculation_remarks = QtWidgets.QPlainTextEdit(self.groupBox_surfaceAreaCalculation_remarks)
        self.plainTextEdit_surfaceAreaCalculation_remarks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_surfaceAreaCalculation_remarks.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_remarks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_remarks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_surfaceAreaCalculation_remarks.setObjectName("plainTextEdit_surfaceAreaCalculation_remarks")
        self.horizontalLayout_33.addWidget(self.plainTextEdit_surfaceAreaCalculation_remarks)
        self.pushButton_surfaceAreaCalculation_AddMaterial = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_AddMaterial.setGeometry(QtCore.QRect(380, 133, 171, 27))
        self.pushButton_surfaceAreaCalculation_AddMaterial.setObjectName("pushButton_surfaceAreaCalculation_AddMaterial")
        self.groupBox_surfaceAreaCalculation_particleDensity = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_particleDensity.setGeometry(QtCore.QRect(380, 241, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_particleDensity.setFont(font)
        self.groupBox_surfaceAreaCalculation_particleDensity.setTitle("")
        self.groupBox_surfaceAreaCalculation_particleDensity.setFlat(False)
        self.groupBox_surfaceAreaCalculation_particleDensity.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_particleDensity.setObjectName("groupBox_surfaceAreaCalculation_particleDensity")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_particleDensity)
        self.horizontalLayout_34.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_surfaceAreaCalculation_particleDensity = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_particleDensity)
        self.label_surfaceAreaCalculation_particleDensity.setObjectName("label_surfaceAreaCalculation_particleDensity")
        self.horizontalLayout_34.addWidget(self.label_surfaceAreaCalculation_particleDensity)
        spacerItem9 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem9)
        self.plainTextEdit_surfaceAreaCalculation_particleDensity = QtWidgets.QPlainTextEdit(self.groupBox_surfaceAreaCalculation_particleDensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_surfaceAreaCalculation_particleDensity.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setSizePolicy(sizePolicy)
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setObjectName("plainTextEdit_surfaceAreaCalculation_particleDensity")
        self.horizontalLayout_34.addWidget(self.plainTextEdit_surfaceAreaCalculation_particleDensity)
        self.groupBox_surfaceAreaCalculation_dateTime = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_dateTime.setEnabled(True)
        self.groupBox_surfaceAreaCalculation_dateTime.setGeometry(QtCore.QRect(110, 203, 140, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_dateTime.setFont(font)
        self.groupBox_surfaceAreaCalculation_dateTime.setTitle("")
        self.groupBox_surfaceAreaCalculation_dateTime.setObjectName("groupBox_surfaceAreaCalculation_dateTime")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_surfaceAreaCalculation_dateTime)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, 9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_surfaceAreaCalculation_dateTime = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_dateTime)
        self.label_surfaceAreaCalculation_dateTime.setObjectName("label_surfaceAreaCalculation_dateTime")
        self.verticalLayout_12.addWidget(self.label_surfaceAreaCalculation_dateTime)
        self.dateTimeEdit_surfaceAreaCalculation_dateTime = QtWidgets.QDateTimeEdit(self.groupBox_surfaceAreaCalculation_dateTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_surfaceAreaCalculation_dateTime.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_surfaceAreaCalculation_dateTime.setSizePolicy(sizePolicy)
        self.dateTimeEdit_surfaceAreaCalculation_dateTime.setObjectName("dateTimeEdit_surfaceAreaCalculation_dateTime")
        self.verticalLayout_12.addWidget(self.dateTimeEdit_surfaceAreaCalculation_dateTime)
        self.groupBox_surfaceAreaCalculation_materialName = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_materialName.setGeometry(QtCore.QRect(380, 166, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_materialName.setFont(font)
        self.groupBox_surfaceAreaCalculation_materialName.setTitle("")
        self.groupBox_surfaceAreaCalculation_materialName.setFlat(False)
        self.groupBox_surfaceAreaCalculation_materialName.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_materialName.setObjectName("groupBox_surfaceAreaCalculation_materialName")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_materialName)
        self.horizontalLayout_35.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_surfaceAreaCalculation_materialName = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_materialName)
        self.label_surfaceAreaCalculation_materialName.setObjectName("label_surfaceAreaCalculation_materialName")
        self.horizontalLayout_35.addWidget(self.label_surfaceAreaCalculation_materialName)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem10)
        self.comboBox_surfaceAreaCalculation_materialName = QtWidgets.QComboBox(self.groupBox_surfaceAreaCalculation_materialName)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_surfaceAreaCalculation_materialName.sizePolicy().hasHeightForWidth())
        self.comboBox_surfaceAreaCalculation_materialName.setSizePolicy(sizePolicy)
        self.comboBox_surfaceAreaCalculation_materialName.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_surfaceAreaCalculation_materialName.setAutoFillBackground(False)
        self.comboBox_surfaceAreaCalculation_materialName.setEditable(True)
        self.comboBox_surfaceAreaCalculation_materialName.setMaxVisibleItems(10)
        self.comboBox_surfaceAreaCalculation_materialName.setFrame(True)
        self.comboBox_surfaceAreaCalculation_materialName.setObjectName("comboBox_surfaceAreaCalculation_materialName")
        self.horizontalLayout_35.addWidget(self.comboBox_surfaceAreaCalculation_materialName)
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon.setGeometry(QtCore.QRect(380, 203, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon.setFont(font)
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon.setTitle("")
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon.setFlat(False)
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_surfaceArea_Argon.setObjectName("groupBox_surfaceAreaCalculation_surfaceArea_Argon")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_surfaceArea_Argon)
        self.horizontalLayout_36.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_surfaceAreaCalculation_surfaceArea_Argon = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_surfaceArea_Argon)
        self.label_surfaceAreaCalculation_surfaceArea_Argon.setObjectName("label_surfaceAreaCalculation_surfaceArea_Argon")
        self.horizontalLayout_36.addWidget(self.label_surfaceAreaCalculation_surfaceArea_Argon)
        spacerItem11 = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem11)
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon = QtWidgets.QPlainTextEdit(self.groupBox_surfaceAreaCalculation_surfaceArea_Argon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setSizePolicy(sizePolicy)
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setObjectName("plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon")
        self.horizontalLayout_36.addWidget(self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon)
        self.groupBox_surfaceAreaCalculation_user = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_user.setGeometry(QtCore.QRect(10, 133, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_user.setFont(font)
        self.groupBox_surfaceAreaCalculation_user.setTitle("")
        self.groupBox_surfaceAreaCalculation_user.setFlat(False)
        self.groupBox_surfaceAreaCalculation_user.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_user.setObjectName("groupBox_surfaceAreaCalculation_user")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_user)
        self.horizontalLayout_37.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(10)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_surfaceAreaCalculation_user = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_user)
        self.label_surfaceAreaCalculation_user.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_surfaceAreaCalculation_user.sizePolicy().hasHeightForWidth())
        self.label_surfaceAreaCalculation_user.setSizePolicy(sizePolicy)
        self.label_surfaceAreaCalculation_user.setObjectName("label_surfaceAreaCalculation_user")
        self.horizontalLayout_37.addWidget(self.label_surfaceAreaCalculation_user)
        spacerItem12 = QtWidgets.QSpacerItem(74, 74, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem12)
        self.plainTextEdit_surfaceAreaCalculation_user = QtWidgets.QPlainTextEdit(self.groupBox_surfaceAreaCalculation_user)
        self.plainTextEdit_surfaceAreaCalculation_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_surfaceAreaCalculation_user.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_user.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_user.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_surfaceAreaCalculation_user.setObjectName("plainTextEdit_surfaceAreaCalculation_user")
        self.horizontalLayout_37.addWidget(self.plainTextEdit_surfaceAreaCalculation_user)
        self.line_9 = QtWidgets.QFrame(self.tab_surfaceAreaCalculation)
        self.line_9.setGeometry(QtCore.QRect(10, 273, 1091, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.groupBox_surfaceAreaCalculation_temperature = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_temperature.setGeometry(QtCore.QRect(10, 168, 350, 32))
        self.groupBox_surfaceAreaCalculation_temperature.setTitle("")
        self.groupBox_surfaceAreaCalculation_temperature.setObjectName("groupBox_surfaceAreaCalculation_temperature")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_temperature)
        self.horizontalLayout_38.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(10)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_surfaceAreaCalculation_temperature = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_temperature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_surfaceAreaCalculation_temperature.sizePolicy().hasHeightForWidth())
        self.label_surfaceAreaCalculation_temperature.setSizePolicy(sizePolicy)
        self.label_surfaceAreaCalculation_temperature.setObjectName("label_surfaceAreaCalculation_temperature")
        self.horizontalLayout_38.addWidget(self.label_surfaceAreaCalculation_temperature)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem13)
        self.plainTextEdit_surfaceAreaCalculation_temperature = QtWidgets.QPlainTextEdit(self.groupBox_surfaceAreaCalculation_temperature)
        self.plainTextEdit_surfaceAreaCalculation_temperature.setObjectName("plainTextEdit_surfaceAreaCalculation_temperature")
        self.horizontalLayout_38.addWidget(self.plainTextEdit_surfaceAreaCalculation_temperature)
        self.groupBox_surfaceAreaCalculation_densityBulk = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_densityBulk.setGeometry(QtCore.QRect(750, 225, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_densityBulk.setFont(font)
        self.groupBox_surfaceAreaCalculation_densityBulk.setTitle("")
        self.groupBox_surfaceAreaCalculation_densityBulk.setFlat(False)
        self.groupBox_surfaceAreaCalculation_densityBulk.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_densityBulk.setObjectName("groupBox_surfaceAreaCalculation_densityBulk")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_densityBulk)
        self.horizontalLayout_39.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_surfaceAreaCalculation_densityBulk = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_densityBulk)
        self.label_surfaceAreaCalculation_densityBulk.setObjectName("label_surfaceAreaCalculation_densityBulk")
        self.horizontalLayout_39.addWidget(self.label_surfaceAreaCalculation_densityBulk)
        spacerItem14 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem14)
        self.plainTextEdit_surfaceAreaCalculation_densityBulk = QtWidgets.QPlainTextEdit(self.groupBox_surfaceAreaCalculation_densityBulk)
        self.plainTextEdit_surfaceAreaCalculation_densityBulk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_surfaceAreaCalculation_densityBulk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_densityBulk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_surfaceAreaCalculation_densityBulk.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainTextEdit_surfaceAreaCalculation_densityBulk.setObjectName("plainTextEdit_surfaceAreaCalculation_densityBulk")
        self.horizontalLayout_39.addWidget(self.plainTextEdit_surfaceAreaCalculation_densityBulk)
        self.pushButton_surfaceAreaCalculation_AddBulk = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_AddBulk.setGeometry(QtCore.QRect(750, 143, 171, 27))
        self.pushButton_surfaceAreaCalculation_AddBulk.setObjectName("pushButton_surfaceAreaCalculation_AddBulk")
        self.groupBox_surfaceAreaCalculation_bulkName = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_bulkName.setGeometry(QtCore.QRect(750, 179, 350, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_bulkName.setFont(font)
        self.groupBox_surfaceAreaCalculation_bulkName.setTitle("")
        self.groupBox_surfaceAreaCalculation_bulkName.setFlat(False)
        self.groupBox_surfaceAreaCalculation_bulkName.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_bulkName.setObjectName("groupBox_surfaceAreaCalculation_bulkName")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.groupBox_surfaceAreaCalculation_bulkName)
        self.horizontalLayout_40.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_surfaceAreaCalculation_bulkName = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_bulkName)
        self.label_surfaceAreaCalculation_bulkName.setObjectName("label_surfaceAreaCalculation_bulkName")
        self.horizontalLayout_40.addWidget(self.label_surfaceAreaCalculation_bulkName)
        spacerItem15 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem15)
        self.comboBox_surfaceAreaCalculation_bulkName = QtWidgets.QComboBox(self.groupBox_surfaceAreaCalculation_bulkName)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_surfaceAreaCalculation_bulkName.sizePolicy().hasHeightForWidth())
        self.comboBox_surfaceAreaCalculation_bulkName.setSizePolicy(sizePolicy)
        self.comboBox_surfaceAreaCalculation_bulkName.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_surfaceAreaCalculation_bulkName.setAutoFillBackground(False)
        self.comboBox_surfaceAreaCalculation_bulkName.setEditable(True)
        self.comboBox_surfaceAreaCalculation_bulkName.setMaxVisibleItems(10)
        self.comboBox_surfaceAreaCalculation_bulkName.setFrame(True)
        self.comboBox_surfaceAreaCalculation_bulkName.setObjectName("comboBox_surfaceAreaCalculation_bulkName")
        self.horizontalLayout_40.addWidget(self.comboBox_surfaceAreaCalculation_bulkName)
        self.groupBox_surfaceAreaCalculation_language = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_language.setGeometry(QtCore.QRect(10, 203, 100, 70))
        self.groupBox_surfaceAreaCalculation_language.setTitle("")
        self.groupBox_surfaceAreaCalculation_language.setObjectName("groupBox_surfaceAreaCalculation_language")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_surfaceAreaCalculation_language)
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_surfaceAreaCalculation_language = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_language)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_surfaceAreaCalculation_language.setFont(font)
        self.label_surfaceAreaCalculation_language.setObjectName("label_surfaceAreaCalculation_language")
        self.verticalLayout_13.addWidget(self.label_surfaceAreaCalculation_language)
        self.checkBox_surfaceAreaCalculation_language_german = QtWidgets.QCheckBox(self.groupBox_surfaceAreaCalculation_language)
        self.checkBox_surfaceAreaCalculation_language_german.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_surfaceAreaCalculation_language_german.setChecked(True)
        self.checkBox_surfaceAreaCalculation_language_german.setTristate(False)
        self.checkBox_surfaceAreaCalculation_language_german.setObjectName("checkBox_surfaceAreaCalculation_language_german")
        self.verticalLayout_13.addWidget(self.checkBox_surfaceAreaCalculation_language_german)
        self.checkBox_surfaceAreaCalculation_language_english = QtWidgets.QCheckBox(self.groupBox_surfaceAreaCalculation_language)
        self.checkBox_surfaceAreaCalculation_language_english.setObjectName("checkBox_surfaceAreaCalculation_language_english")
        self.verticalLayout_13.addWidget(self.checkBox_surfaceAreaCalculation_language_english)
        self.line_10 = QtWidgets.QFrame(self.tab_surfaceAreaCalculation)
        self.line_10.setGeometry(QtCore.QRect(730, 133, 20, 140))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime.setGeometry(QtCore.QRect(250, 203, 111, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime.setFont(font)
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime.setTitle("")
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime.setFlat(False)
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime.setCheckable(False)
        self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime.setObjectName("groupBox_surfaceAreaCalculation_OneTwoRelaxationTime")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_surfaceAreaCalculation_OneTwoRelaxationTime = QtWidgets.QLabel(self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime)
        self.label_surfaceAreaCalculation_OneTwoRelaxationTime.setObjectName("label_surfaceAreaCalculation_OneTwoRelaxationTime")
        self.verticalLayout_14.addWidget(self.label_surfaceAreaCalculation_OneTwoRelaxationTime)
        self.checkBox_surfaceAreaCalculation_TwoRelaxationTime = QtWidgets.QCheckBox(self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime)
        self.checkBox_surfaceAreaCalculation_TwoRelaxationTime.setChecked(True)
        self.checkBox_surfaceAreaCalculation_TwoRelaxationTime.setObjectName("checkBox_surfaceAreaCalculation_TwoRelaxationTime")
        self.verticalLayout_14.addWidget(self.checkBox_surfaceAreaCalculation_TwoRelaxationTime)
        self.checkBox_surfaceAreaCalculation_OneRelaxationTime = QtWidgets.QCheckBox(self.groupBox_surfaceAreaCalculation_OneTwoRelaxationTime)
        self.checkBox_surfaceAreaCalculation_OneRelaxationTime.setObjectName("checkBox_surfaceAreaCalculation_OneRelaxationTime")
        self.verticalLayout_14.addWidget(self.checkBox_surfaceAreaCalculation_OneRelaxationTime)
        self.pushButton_surfaceAreaCalculation_RemoveSelectedMeasrementFiles = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_RemoveSelectedMeasrementFiles.setGeometry(QtCore.QRect(219, 504, 190, 30))
        self.pushButton_surfaceAreaCalculation_RemoveSelectedMeasrementFiles.setObjectName("pushButton_surfaceAreaCalculation_RemoveSelectedMeasrementFiles")
        self.groupBox_surfaceAreaCalculation_mesurementFiles = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_mesurementFiles.setGeometry(QtCore.QRect(10, 330, 1090, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_surfaceAreaCalculation_mesurementFiles.sizePolicy().hasHeightForWidth())
        self.groupBox_surfaceAreaCalculation_mesurementFiles.setSizePolicy(sizePolicy)
        self.groupBox_surfaceAreaCalculation_mesurementFiles.setObjectName("groupBox_surfaceAreaCalculation_mesurementFiles")
        self.tableView_surfaceAreaCalculation_mesurementFiles = QtWidgets.QTableView(self.groupBox_surfaceAreaCalculation_mesurementFiles)
        self.tableView_surfaceAreaCalculation_mesurementFiles.setGeometry(QtCore.QRect(10, 20, 1080, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableView_surfaceAreaCalculation_mesurementFiles.setFont(font)
        self.tableView_surfaceAreaCalculation_mesurementFiles.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_surfaceAreaCalculation_mesurementFiles.setWordWrap(True)
        self.tableView_surfaceAreaCalculation_mesurementFiles.setObjectName("tableView_surfaceAreaCalculation_mesurementFiles")
        self.pushButton_surfaceAreaCalculation_AddMesurementFiles = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_AddMesurementFiles.setGeometry(QtCore.QRect(20, 504, 190, 30))
        self.pushButton_surfaceAreaCalculation_AddMesurementFiles.setObjectName("pushButton_surfaceAreaCalculation_AddMesurementFiles")
        self.pushButton_surfaceAreaCalculation_RemoveAllMesurementFiles = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_RemoveAllMesurementFiles.setGeometry(QtCore.QRect(20, 540, 190, 30))
        self.pushButton_surfaceAreaCalculation_RemoveAllMesurementFiles.setObjectName("pushButton_surfaceAreaCalculation_RemoveAllMesurementFiles")
        self.plainTextEdit_surfaceAreaCalculation_RemoveSelectedFilesMeasrementFiles = QtWidgets.QPlainTextEdit(self.tab_surfaceAreaCalculation)
        self.plainTextEdit_surfaceAreaCalculation_RemoveSelectedFilesMeasrementFiles.setGeometry(QtCore.QRect(220, 540, 188, 30))
        self.plainTextEdit_surfaceAreaCalculation_RemoveSelectedFilesMeasrementFiles.setObjectName("plainTextEdit_surfaceAreaCalculation_RemoveSelectedFilesMeasrementFiles")
        self.pushButton_surfaceAreaCalculation_run = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_run.setGeometry(QtCore.QRect(920, 512, 130, 57))
        self.pushButton_surfaceAreaCalculation_run.setObjectName("pushButton_surfaceAreaCalculation_run")
        self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles = QtWidgets.QGroupBox(self.tab_surfaceAreaCalculation)
        self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles.setGeometry(QtCore.QRect(10, 6, 1090, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles.sizePolicy().hasHeightForWidth())
        self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles.setSizePolicy(sizePolicy)
        self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles.setObjectName("groupBox_surfaceAreaCalculation_ReferenceMesurementFiles")
        self.tableView_surfaceAreaCalculation_ReferenceMesurementFiles = QtWidgets.QTableView(self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles)
        self.tableView_surfaceAreaCalculation_ReferenceMesurementFiles.setGeometry(QtCore.QRect(10, 20, 1080, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableView_surfaceAreaCalculation_ReferenceMesurementFiles.setFont(font)
        self.tableView_surfaceAreaCalculation_ReferenceMesurementFiles.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_surfaceAreaCalculation_ReferenceMesurementFiles.setWordWrap(True)
        self.tableView_surfaceAreaCalculation_ReferenceMesurementFiles.setObjectName("tableView_surfaceAreaCalculation_ReferenceMesurementFiles")
        self.pushButton_surfaceAreaCalculation_RemoveReferenceMeasrementFile = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_RemoveReferenceMeasrementFile.setGeometry(QtCore.QRect(300, 92, 261, 30))
        self.pushButton_surfaceAreaCalculation_RemoveReferenceMeasrementFile.setObjectName("pushButton_surfaceAreaCalculation_RemoveReferenceMeasrementFile")
        self.pushButton_surfaceAreaCalculation_AddReferenceMesurementFile = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_AddReferenceMesurementFile.setGeometry(QtCore.QRect(10, 92, 261, 30))
        self.pushButton_surfaceAreaCalculation_AddReferenceMesurementFile.setObjectName("pushButton_surfaceAreaCalculation_AddReferenceMesurementFile")
        self.line_6 = QtWidgets.QFrame(self.tab_surfaceAreaCalculation)
        self.line_6.setGeometry(QtCore.QRect(433, 510, 3, 60))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_surfaceAreaCalculation_SetUpdateSelectedWeights = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_SetUpdateSelectedWeights.setGeometry(QtCore.QRect(657, 507, 190, 30))
        self.pushButton_surfaceAreaCalculation_SetUpdateSelectedWeights.setObjectName("pushButton_surfaceAreaCalculation_SetUpdateSelectedWeights")
        self.comboBox_surfaceAreaCalculation_selectWeighInData = QtWidgets.QComboBox(self.tab_surfaceAreaCalculation)
        self.comboBox_surfaceAreaCalculation_selectWeighInData.setGeometry(QtCore.QRect(461, 506, 188, 30))
        self.comboBox_surfaceAreaCalculation_selectWeighInData.setEditable(False)
        self.comboBox_surfaceAreaCalculation_selectWeighInData.setObjectName("comboBox_surfaceAreaCalculation_selectWeighInData")
        self.plainTextEdit_surfaceAreaCalculation_SetUpdateWeights = QtWidgets.QPlainTextEdit(self.tab_surfaceAreaCalculation)
        self.plainTextEdit_surfaceAreaCalculation_SetUpdateWeights.setGeometry(QtCore.QRect(658, 540, 188, 30))
        self.plainTextEdit_surfaceAreaCalculation_SetUpdateWeights.setObjectName("plainTextEdit_surfaceAreaCalculation_SetUpdateWeights")
        self.line_7 = QtWidgets.QFrame(self.tab_surfaceAreaCalculation)
        self.line_7.setGeometry(QtCore.QRect(884, 510, 3, 60))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_surfaceAreaCalculation_SetUpdateWeights = QtWidgets.QPushButton(self.tab_surfaceAreaCalculation)
        self.pushButton_surfaceAreaCalculation_SetUpdateWeights.setGeometry(QtCore.QRect(460, 540, 190, 30))
        self.pushButton_surfaceAreaCalculation_SetUpdateWeights.setObjectName("pushButton_surfaceAreaCalculation_SetUpdateWeights")
        self.tabWinget.addTab(self.tab_surfaceAreaCalculation, "")
        MainWindow_NMR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_NMR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow_NMR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_NMR)
        self.statusbar.setObjectName("statusbar")
        MainWindow_NMR.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow_NMR)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow_NMR)
        self.actionExport.setObjectName("actionExport")
        self.menuMain.addAction(self.actionImport)
        self.menuMain.addAction(self.actionExport)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow_NMR)
        self.tabWinget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_NMR)

    def retranslateUi(self, MainWindow_NMR):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_NMR.setWindowTitle(_translate("MainWindow_NMR", "NMR"))
        self.tabWinget.setToolTip(_translate("MainWindow_NMR", "<html><head/><body><p>Test</p></body></html>"))
        self.label_temperature.setText(_translate("MainWindow_NMR", "Temperature "))
        self.plainTextEdit_temperature.setPlaceholderText(_translate("MainWindow_NMR", "Enter Temperature in °C"))
        self.label_user.setText(_translate("MainWindow_NMR", "User"))
        self.plainTextEdit_user.setPlaceholderText(_translate("MainWindow_NMR", "Enter user here"))
        self.label_language.setText(_translate("MainWindow_NMR", "Language"))
        self.checkBox_language_german.setText(_translate("MainWindow_NMR", "German"))
        self.checkBox_language_english.setText(_translate("MainWindow_NMR", "English"))
        self.label_dateTime.setText(_translate("MainWindow_NMR", "Date"))
        self.dateTimeEdit_dateTime.setDisplayFormat(_translate("MainWindow_NMR", "dd.MM.yyyy"))
        self.label_materialName.setText(_translate("MainWindow_NMR", "Material Name"))
        self.label_evaluation.setText(_translate("MainWindow_NMR", "Evaluation"))
        self.checkBox_evaluation_single.setText(_translate("MainWindow_NMR", "Single"))
        self.checkBox_evaluation_other.setText(_translate("MainWindow_NMR", "Other"))
        self.label_bulkName.setText(_translate("MainWindow_NMR", "Bulk Name"))
        self.label_remarks.setText(_translate("MainWindow_NMR", "remarks"))
        self.plainTextEdit_remarks.setToolTip(_translate("MainWindow_NMR", "E.g. single"))
        self.plainTextEdit_remarks.setPlaceholderText(_translate("MainWindow_NMR", "Enter optional remarks here"))
        self.label_surfaceArea_Argon.setText(_translate("MainWindow_NMR", "SurfaceArea Argon"))
        self.plainTextEdit_surfaceArea_Argon.setPlaceholderText(_translate("MainWindow_NMR", "e.g.: 47.2"))
        self.label_densityBulk.setText(_translate("MainWindow_NMR", "Density Bulk"))
        self.plainTextEdit_densityBulk.setPlaceholderText(_translate("MainWindow_NMR", "e.g.: 1"))
        self.groupBox_mesurementFiles.setTitle(_translate("MainWindow_NMR", "Mesurement Files"))
        self.pushButton_AddMesurementFiles.setText(_translate("MainWindow_NMR", "Add Files"))
        self.pushButton_RemoveAllMesurementFiles.setText(_translate("MainWindow_NMR", "Remove all Files"))
        self.pushButton_run_MeasurementFile.setText(_translate("MainWindow_NMR", "RUN"))
        self.label_particleDensity.setText(_translate("MainWindow_NMR", "Particle Density"))
        self.plainTextEdit_particleDensity.setPlaceholderText(_translate("MainWindow_NMR", "e.g.: 2.14"))
        self.pushButton_AddMaterial.setText(_translate("MainWindow_NMR", "Add Material"))
        self.pushButton_RemoveMaterial.setText(_translate("MainWindow_NMR", "Remove Material"))
        self.pushButton_AddBulk.setText(_translate("MainWindow_NMR", "Add Bulk"))
        self.pushButton_RemoveBulk.setText(_translate("MainWindow_NMR", "Remove Bulk"))
        self.pushButton_RemoveSelectedMeasrementFiles.setText(_translate("MainWindow_NMR", "Remove selected Files"))
        self.plainTextEdit_RemoveSelectedFilesMeasrementFiles.setPlaceholderText(_translate("MainWindow_NMR", "Remove: e.g.: 2,3,6"))
        self.pushButton_SetUpdateWeights.setText(_translate("MainWindow_NMR", "Set / Update weights"))
        self.plainTextEdit_SetUpdateWeights.setPlaceholderText(_translate("MainWindow_NMR", "Empty = all, e.g: 2,5,8"))
        self.pushButton_SetUpdateSelectedWeights.setText(_translate("MainWindow_NMR", "Update seleceted weights"))
        self.tabWinget.setTabText(self.tabWinget.indexOf(self.Tab_referenceMesurement), _translate("MainWindow_NMR", "Calibration line (AcomArea)"))
        self.checkBox_comperisonPlots_T1.setText(_translate("MainWindow_NMR", "Create T1 compersion"))
        self.checkBox_comperisonPlots_T2.setText(_translate("MainWindow_NMR", "Create T2 compersion"))
        self.label_comperisonPlots_T1PlotName.setText(_translate("MainWindow_NMR", "T1 Plot name:"))
        self.label_comperisonPlots_T2PlotName.setText(_translate("MainWindow_NMR", "T2 Plot name:"))
        self.label_comperisonPlots_language.setText(_translate("MainWindow_NMR", "Language"))
        self.checkBox_comperisonPlots_language_german.setText(_translate("MainWindow_NMR", "German"))
        self.checkBox_comperisonPlots_language_english.setText(_translate("MainWindow_NMR", "English"))
        self.label_T1_comperisonPlots_calculationOfVolumeFraction.setText(_translate("MainWindow_NMR", "T1 calculation of Volume Fraction:"))
        self.label_T2_comperisonPlots_calculationOfVolumeFraction.setText(_translate("MainWindow_NMR", "T2 calculation of Volume Fraction:"))
        self.groupBox_comperisonPlots_referenceMeasurementFiles.setTitle(_translate("MainWindow_NMR", "Reference Measurement Files"))
        self.pushButton_comperisonPlots_RemoveSelectedReferenceMeasrementFiles.setText(_translate("MainWindow_NMR", "Remove Selected Files"))
        self.pushButton_comperisonPlots_AddReferenceReferenceMesurementFiles.setText(_translate("MainWindow_NMR", "Add Files"))
        self.pushButton_comperisonPlots_RemoveAllReferenceMesurementFiles.setText(_translate("MainWindow_NMR", "Remove all Files"))
        self.plainTextEdit_comperisonPlots_RemoveSelectedFilesReferenceMeasrementFiles.setPlaceholderText(_translate("MainWindow_NMR", "Files to Remove, e.g.: 2,3,6"))
        self.pushButton_ComerisonPlots_run.setText(_translate("MainWindow_NMR", "RUN"))
        self.tabWinget.setTabText(self.tabWinget.indexOf(self.tab_comperisonPlots), _translate("MainWindow_NMR", "Comperison Plots"))
        self.pushButton_surfaceAreaCalculation_RemoveMaterial.setText(_translate("MainWindow_NMR", "Remove Material"))
        self.pushButton_surfaceAreaCalculation_RemoveBulk.setText(_translate("MainWindow_NMR", "Remove Bulk"))
        self.label_surfaceAreaCalculation_remarks.setText(_translate("MainWindow_NMR", "remarks"))
        self.plainTextEdit_surfaceAreaCalculation_remarks.setToolTip(_translate("MainWindow_NMR", "E.g. single"))
        self.plainTextEdit_surfaceAreaCalculation_remarks.setPlaceholderText(_translate("MainWindow_NMR", "Enter optional remarks here"))
        self.pushButton_surfaceAreaCalculation_AddMaterial.setText(_translate("MainWindow_NMR", "Add Material"))
        self.label_surfaceAreaCalculation_particleDensity.setText(_translate("MainWindow_NMR", "Particle Density"))
        self.plainTextEdit_surfaceAreaCalculation_particleDensity.setPlaceholderText(_translate("MainWindow_NMR", "e.g.: 2.14"))
        self.label_surfaceAreaCalculation_dateTime.setText(_translate("MainWindow_NMR", "Date"))
        self.dateTimeEdit_surfaceAreaCalculation_dateTime.setDisplayFormat(_translate("MainWindow_NMR", "dd.MM.yyyy"))
        self.label_surfaceAreaCalculation_materialName.setText(_translate("MainWindow_NMR", "Material Name"))
        self.label_surfaceAreaCalculation_surfaceArea_Argon.setText(_translate("MainWindow_NMR", "SurfaceArea Argon"))
        self.plainTextEdit_surfaceAreaCalculation_surfaceArea_Argon.setPlaceholderText(_translate("MainWindow_NMR", "e.g.: 47.2"))
        self.label_surfaceAreaCalculation_user.setText(_translate("MainWindow_NMR", "User"))
        self.plainTextEdit_surfaceAreaCalculation_user.setPlaceholderText(_translate("MainWindow_NMR", "Enter user here"))
        self.label_surfaceAreaCalculation_temperature.setText(_translate("MainWindow_NMR", "Temperature "))
        self.plainTextEdit_surfaceAreaCalculation_temperature.setPlaceholderText(_translate("MainWindow_NMR", "Enter Temperature in °C"))
        self.label_surfaceAreaCalculation_densityBulk.setText(_translate("MainWindow_NMR", "Density Bulk"))
        self.plainTextEdit_surfaceAreaCalculation_densityBulk.setPlaceholderText(_translate("MainWindow_NMR", "e.g.: 1"))
        self.pushButton_surfaceAreaCalculation_AddBulk.setText(_translate("MainWindow_NMR", "Add Bulk"))
        self.label_surfaceAreaCalculation_bulkName.setText(_translate("MainWindow_NMR", "Bulk Name"))
        self.label_surfaceAreaCalculation_language.setText(_translate("MainWindow_NMR", "Language"))
        self.checkBox_surfaceAreaCalculation_language_german.setText(_translate("MainWindow_NMR", "German"))
        self.checkBox_surfaceAreaCalculation_language_english.setText(_translate("MainWindow_NMR", "English"))
        self.label_surfaceAreaCalculation_OneTwoRelaxationTime.setText(_translate("MainWindow_NMR", "Relaxation"))
        self.checkBox_surfaceAreaCalculation_TwoRelaxationTime.setText(_translate("MainWindow_NMR", "One"))
        self.checkBox_surfaceAreaCalculation_OneRelaxationTime.setText(_translate("MainWindow_NMR", "Two"))
        self.pushButton_surfaceAreaCalculation_RemoveSelectedMeasrementFiles.setText(_translate("MainWindow_NMR", "Remove Selected Files"))
        self.groupBox_surfaceAreaCalculation_mesurementFiles.setTitle(_translate("MainWindow_NMR", "Mesurement Files"))
        self.pushButton_surfaceAreaCalculation_AddMesurementFiles.setText(_translate("MainWindow_NMR", "Add Files"))
        self.pushButton_surfaceAreaCalculation_RemoveAllMesurementFiles.setText(_translate("MainWindow_NMR", "Remove all Files"))
        self.plainTextEdit_surfaceAreaCalculation_RemoveSelectedFilesMeasrementFiles.setPlaceholderText(_translate("MainWindow_NMR", "Remove, e.g.: 2,3,6"))
        self.pushButton_surfaceAreaCalculation_run.setText(_translate("MainWindow_NMR", "RUN"))
        self.groupBox_surfaceAreaCalculation_ReferenceMesurementFiles.setTitle(_translate("MainWindow_NMR", "Reference Measurement File"))
        self.pushButton_surfaceAreaCalculation_RemoveReferenceMeasrementFile.setText(_translate("MainWindow_NMR", "Remove File"))
        self.pushButton_surfaceAreaCalculation_AddReferenceMesurementFile.setText(_translate("MainWindow_NMR", "Add File"))
        self.pushButton_surfaceAreaCalculation_SetUpdateSelectedWeights.setText(_translate("MainWindow_NMR", "Update seleceted weights"))
        self.plainTextEdit_surfaceAreaCalculation_SetUpdateWeights.setPlaceholderText(_translate("MainWindow_NMR", "Update: e.g: 2,5,8"))
        self.pushButton_surfaceAreaCalculation_SetUpdateWeights.setText(_translate("MainWindow_NMR", "Set / Update all weights"))
        self.tabWinget.setTabText(self.tabWinget.indexOf(self.tab_surfaceAreaCalculation), _translate("MainWindow_NMR", "Surface Area Calculation"))
        self.menuMain.setTitle(_translate("MainWindow_NMR", "File"))
        self.actionImport.setText(_translate("MainWindow_NMR", "Import"))
        self.actionExport.setText(_translate("MainWindow_NMR", "Export "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_NMR = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_NMR()
    ui.setupUi(MainWindow_NMR)
    MainWindow_NMR.show()
    sys.exit(app.exec_())

